version: '2'
services:
  redis:
      image: redis:3.2.0
      ports:
        - 6379


  falcon:
    build: ./falcon
    environment: 
        SOMETHING: 123
    links:
        - redis:redis
    ports:
        - 9000:9000
    depends_on:
        - redis
    environment:
        REDIS_HOST: redis

  worker1:
    build: ./worker
    command: python mara-worker.py 1
    links: 
      - redis
    volumes:
      - worker_data:/code/
    environment:
        REDIS_HOST: redis
    depends_on:
        - redis


  nginx:
    build: ./nginx
    links:
        - worker1:worker1
        - falcon:falcon
    ports:
        - 81:80
    volumes_from:
        - worker1
    depends_on:
        - worker1
        - redis

volumes:
  worker_data: # declare a volume named worker_data